# Site
repository: verakai/verakai.github.io
favicon: images/favicon.ico

# Personal info
name: Rodolfo Maciéczyk
title: Data Scientist & Entrepreneur | Zürich, Switzerland
email: rmache@gmail.com 

# Social links
github_username:  verakai
linkedin_username: rmacieczyk

# About Section
about_title: About Me 
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  I'm a data scientist and passionate entrepreneur with background in astronomy. Experienced in statistical models with Python and relevant libraries ( scikit-learn, Numpy, Pandas, TenserFlow, etc.). Skilled in implementing A/B testing and <mark>Machine Learning</mark> solutions to solve business problems. Reinforcement learning enthusiast. Extensive background in entrepreneurship. Rock climber, skier and yoga junkie.
  

#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - Lists
#    - Tables
#    - Links
#    - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

  **Advanced**: *Python, Neural Networks (RNN, CNN, LSTM, etc.), Pandas, SQL, Data Cleaning, Data Visualization, Regression Algorithms, Classification algorithms, Numpy, Matplotlib, Probability & Statistics, Data Manipulation*


  **Proficient**: *TensorFlow, Keras, Supervised & Unsupervised Learning, Clustering algorithms, Data Wrangling, Machine Learning pipelines, Google Cloud Platform*


  **Expert**: *Technical writing in Spanish and English Language, fluent in Spanish, English and Swiss german languages, running & skiing*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
